  - name: Install Apache server and other packages
    yum: name={{ item }} state=present
    with_items:
      - httpd
      - php
      - mc
      - vim
      - telnet
      - git

  - name: ensure Apache is running and starts on boot
    service: name=httpd state=started enabled=yes

  - name: Check if the repo already exists
    stat: path=/home/vagrant/RainGauge
    register: check_rg_path

  - name: clone repo //github.com/box/RainGauge.git
    command: git clone git://github.com/box/RainGauge.git
    when: check_rg_path.stat.exists == false

  - name: install Rain Gauge web app 
    command: cp -r /home/vagrant/RainGauge /var/www/html/ 

  - name: set the premission on 'collected' dir
    action: file path=/var/www/html/RainGauge/collected state=directory owner=apache group=apache mode=0775


